### ISSUE TITLE
Safari browser - cursor appears behind the placeholder

### ISSUE THREAD

**Issue by mkerstens** [w0rm/jquery.placeholder#6]
In safari (5.1.7) the cursor appears behind the placeholder text. 
Which looks really strange.

**Comment by mkerstens** [comment]
Forgot to mention that I'm using the <input> autofocus attribute, to let the input automatically get focus when the page loads. That why I also want to use your placeholder plugin.

**Comment by w0rm** [comment]
@Chazz09 sorry for the late reply. What you've explained seems like desired behaviour I'm trying to accomplish here — do not hide placeholder on focus, hide it only when user inputs text. 
All new browsers including Safari have this behavior and this placeholder plugin should not be activated for them unless you set the `force` option.
